-- Query generated by ChatGPT
-- By OpenAI's ChatGPT

/*
View stg_parkrun_all_v:
- EVENTDATE: Date the event took place
- EVENTNUM: The event number where 1 is the first event and so on
- TOTALATHLETES: The total number of people that ran the event
- Position: The position of the athlete in this row within the event on the date shown
- "parkrunID": The unique ID of the athlete
- "Name": The name of the athlete - may not be unique
- Gender: The gender of the athlete
- AgeBracket: The 5-year age bracket of the athlete
- Club: The running club of the athlete
- TimeMin: the time they took in the event on the eventdate in minutes
- TimeSec: The second portion of their time as per TimeMin
- TOTALSEC: The total seconds the athlete took in the event
- DISPLAYTIME: A string representation of the athlete's time on that date
- MINS_5_BUCKET: An ID to place each time in a 5-minute bucket
*/

SELECT
    ROW_NUMBER() OVER (ORDER BY MIN(TOTALSEC)) AS ranking,
    "parkrunID",
    "Name",
    MIN(TOTALSEC) AS best_time,
    FLOOR(MIN(TOTALSEC) / 60) AS best_time_minutes,
    MOD(MIN(TOTALSEC), 60) AS best_time_seconds
FROM
    stg_parkrun_all_v
GROUP BY
    "parkrunID",
    "Name"
ORDER BY
    best_time
LIMIT 1000;
