-- Query to get the best time for each athlete over all events with ranking
-- Generated by the **Copilot** AI model
WITH RankedTimes AS (
    SELECT
        "parkrunID" AS "Athlete ID",
        "Name" AS "Athlete Name",
        MIN("TOTALSEC") AS "Best Time (Seconds)",
        RANK() OVER (ORDER BY MIN("TOTALSEC")) AS "Rank"
    FROM
        stg_parkrun_all_v
    GROUP BY
        "parkrunID", "Name"
)
SELECT
    "Athlete ID",
    "Athlete Name",
    "Best Time (Seconds)",
    CONCAT(
        FLOOR("Best Time (Seconds)" / 60), ' min ',
        MOD("Best Time (Seconds)", 60), ' sec'
    ) AS "Best Time (Minutes:Seconds)",
    "Rank"
FROM
    RankedTimes
WHERE
    "Rank" <= 1000
ORDER BY
    "Rank";
