-- This query, generated by Bard, a large language model from Google AI, 
-- finds the fastest time for each athlete in the 'stg_parkrun_all_v' table 
-- and ranks them based on their fastest time. It then returns the top 1000 
-- ranked athletes with their ranking, parkrunID, name, fastest time in 
-- whole minutes, and fastest time in seconds.

with ranked as (
  SELECT 
    "parkrunID", 
    "Name", -- replaced "name" with "Name" as requested
    MIN(TOTALSEC) as fastest_time,
    ROW_NUMBER() OVER (ORDER BY MIN(TOTALSEC) ASC) AS ranking
  FROM stg_parkrun_all_v
  GROUP BY "parkrunID", "Name"
)
SELECT 
  ranking,
  "parkrunID",
  "Name",
  FLOOR(fastest_time / 60) AS mins,
  fastest_time % 60 AS secs
FROM ranked
WHERE ranking <= 1000
ORDER BY ranking;